import { Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { ProjectShowcase } from "../components/atoms/ProjectShowcase/ProjectShowcase";
import { TitleBanner } from "../components/molecules/TitleBanner/TitleBanner";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex flexDir="column" my="5%" mx="20%">
          <TitleBanner />
          <Flex columnGap="5px" flexDir="row" my="10px">
            <ProjectShowcase />
            <ProjectShowcase />
            <ProjectShowcase />
          </Flex>
        </Flex>
      </main>
    </>
  );
};

export default Home;
