import { getAllPosts, Post } from "lib/api";
import Head from "next/head";
import { BlogPost } from "../components/atoms";

interface HomeProps {
  allPosts: Post[];
}

const Home = ({ allPosts }: HomeProps): JSX.Element => {
  console.log(allPosts);
  return (
    <>
      <Head>
        <title>Spencer Mehta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{ padding: "0 33%" }}>
          <h1>Spencer Mehta</h1>
          <p>Software Engineer @ Theodo UK</p>
          <div>
            <h2>Blog posts</h2>
            {allPosts.map((post) => (
              <BlogPost key={post.slug} post={post} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export const getStaticProps = () => {
  const allPosts = getAllPosts(["title", "date", "slug", "author", "excerpt"]);

  return {
    props: { allPosts },
  };
};

export default Home;
