name: Deploy

on:
  push:
    branches:
      - main

env:
  CI: true
  NODE_VERSION: 14

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          cd frontend
          yarn install --immutable
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::781202196452:role/blog-deploy-role
          role-duration-seconds: 900
          aws-region: us-east-1
      - name: Deploy app
        run: |
          cd frontend
          yarn deploy
        shell: bash
